### ISSUE TITLE
最大长度限制200字符

### ISSUE THREAD

**Issue by TechStylex** [windily-cloud/obsidian-AGtable#3]
提个bug哈，双击编辑框，只能输入200个字符。打开开发者模式显示如下：
![image](https://user-images.githubusercontent.com/6605184/162688481-9f6861a8-fb0b-4fce-b17a-c1ce60b0505d.png)

**Comment by windily-cloud** [comment]
这个问题早就注意到并且修改了，只是没上传。最新版我已经调成了10000，应该够了吧😊

**Comment by TechStylex** [comment]
太棒了
