### ISSUE TITLE
如何设置字体大小？表格里的字太小了

### ISSUE THREAD

**Issue by TechStylex** [windily-cloud/obsidian-AGtable#5]
如何设置字体大小？表格里的字太小了

**Comment by TechStylex** [comment]
我替换了font-size为18px，就出现了另外一个帖子里的bug，不知道是不是这个导致的
https://github.com/windily-cloud/obsidian-AGtable/issues/4

**Comment by windily-cloud** [comment]
选择器是`#table-body .ag-center-cols-container .ag-row`，把`font-size`改大就好了。我也改了一下，并没有出现你说的情况。
