### ISSUE TITLE
能否在表头提供筛选功能

### ISSUE THREAD

**Issue by lbgws2** [windily-cloud/obsidian-AGtable#6]
在AGtable的官网demo看到筛选功能很强大,可以从字段的任意位置匹配输入词

对于表格来说,排序与筛选是两项很基础,很重要的功能

如果markdown表格能实现筛选,将是一个突破性的功能,目前我在任何一个笔记类产品均没有发现这个功能

**Comment by windily-cloud** [comment]
拖动排序不是已经实现了吗？筛选的话直接搜应该直接ctrl f也能搜吧。另外，表格可能有更好的插件，比如notion like table，db folder，你可以试试。

**Comment by windily-cloud** [comment]
该版本agtable已经能筛选了
